name: CI
on:
  push:
    paths-ignore:
    - '.vscode'
    - '*.md'
    - 'LICENCE'

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x, 10.x]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install

    - name: Run build
      run: npm run build:linux

    - name: Moving build to artifacts directory
      run: bash ./scripts/move-files.sh linux

    - name: Upload linux amd64 deb
      uses: actions/upload-artifact@v1
      with:
        name: "linux-${{ matrix.node_version }}-thermal-linux-amd64"
        path: "dist/artifacts/thermal-linux-amd64-*.deb"

